{"url": "https://towardsdatascience.com/causal-inference-with-synthetic-control-in-python-4a79ee636325", "time": 1683018956.459423, "path": "towardsdatascience.com/causal-inference-with-synthetic-control-in-python-4a79ee636325/", "scrape_status": {"code": 4, "message": "invalid response status code", "resp_status_code": 429}}