{"url": "https://towardsdatascience.com/clash-of-python-data-visualization-libraries-c4f668a279f", "time": 1683018810.158881, "path": "towardsdatascience.com/clash-of-python-data-visualization-libraries-c4f668a279f/", "scrape_status": {"code": 4, "message": "invalid response status code", "resp_status_code": 429}}