{"url": "https://towardsdatascience.com/how-to-define-custom-exception-classes-in-python-bfa346629bca", "time": 1683002677.927414, "path": "towardsdatascience.com/how-to-define-custom-exception-classes-in-python-bfa346629bca/", "webpage": {"metadata": {"title": "How to Define Custom Exception Classes in Python | by Stephen Fordham | Towards Data Science", "h1": "How to Define Custom Exception Classes in Python", "description": "In Python, we have the ability to create our own exception classes. The construction of custom exception classes can enrich our class design. A custom error class could logs errors, inspect an\u2026"}, "outgoing_paragraph_urls": [{"url": "https://gist.github.com/StephenFordham/8ea287187a0fde02a8ee82d5a1f2039f", "anchor_text": "here", "paragraph_index": 9}, {"url": "https://gist.github.com/StephenFordham/549973c9a6099914d2758e3e144e19fa", "anchor_text": "here", "paragraph_index": 27}, {"url": "https://github.com/StephenFordham", "anchor_text": "https://github.com/StephenFordham", "paragraph_index": 30}], "all_paragraphs": ["In Python, we have the ability to create our own exception classes. The construction of custom exception classes can enrich our class design. A custom error class could logs errors, inspect an object. It is up to us what the exception class does, although a custom class will not usually do a great deal more than display a message.", "The type of error is itself significant of course, and we often create our own error types to indicate a particular situation that Python does not usually cover. In this way, users of the class who encounter the error will know exactly what is going on.", "This tutorial piece will consist of two parts. Firstly, an exception class will be defined in isolation. The second part will showcase how we can integrate custom exception classes into our Python programs, and demonstrate how this can enhance the usability of the classes we design.", "When we raise an exception, we are actually creating an exception instance and printing it at the same time. Let's dissect the custom exception class shown below.", "In the MyCustomError class above, there are two magic methods, __init__ and __str__ that are automatically called during the exception handling process. Init is the method called when an instance is created and str is the magic method called when an instance is printed. Therefore, when an exception is raised, they are usually called in close succession. The raise statement in Python puts the programs into an error condition.", "The __init__ method has *args in its arguments list. The *args is a special pattern matching mode that is used in functions and methods. It allows multiple arguments to be passed, and stores the arguments passed as a tuple, but it also allows no arguments to be passed at all.", "In our case, we are saying, that if any arguments are passed to the MyCustomError constructor, we will take the first argument passed, and assign it to an attribute in the object called message. If no arguments are passed, None will be assigned to the message attribute.", "In the first example, MyCustomError is being raised without any arguments, so None will be set to the message attribute in the object. The str method will be called and will print the message \u2018MyCustomError message has been raised\u2019.", "In the second example, MyCustomError is passed with a string argument of \u2018We have a problem\u2019. This is set as the message attribute in the object and printed in the error message when the exception is raised.", "The code for the MyCustomError exception class can be found here.", "Let's progress now, and demonstrate how custom error classes can easily and usefully be incorporated into our own programs. To begin, I will create a slightly contrived example. In this fictitious example, I will create a custom dictionary, that can only accept either integers or floats as its values.", "If the user attempts to set any other data type as the value in this dictionary, an exception will be raised. The exception raised will usefully inform the user of how the dictionary is intended to be used. In our case, a message explicitly informing the user that only integers and floats can be set as values in this custom dictionary.", "We have to be mindful that when we create a custom dictionary there are two places where values can be added. The first is when the object is constructed in the init method (the object could already be assigned with keys and values), and the other is when we set a key and value in the dictionary. In both of these places, we need to write code that ensures that the value can only be of type int or float.", "To begin, I define a class called CustomIntFloatDict which inherits from the built-in dict class. dict is passed in the arguments list in the parentheses following the name of the class, CustomIntFloatDict.", "If an instance of the CustomIntFloatDict is created, and no arguments are passed to the key and value parameters, they will be set to None. The if expression evaluates that if either the key is None or the value is None, the get_dict() method will be called on the object, which will return the empty_dict attribute of the object, which points to an empty list. Remember that class attributes are available to all instances of the class.", "The intention of this class is to have the user pass a list or tuple with the keys and values inside. If the user enters a list or tuple for the keys and values, the two iterables will be zipped together using the python zip function. The zipped variable which points to the zip object can be iterated over, and the tuples can be unpacked. As we iterate through the tuples, I check to see whether the val is an instance of the int or float class. If it is not, I raise a custom IntFloatValueError with val passed as an argument.", "When we raise a IntFloatValueError exception, we are creating an instance of the IntFloatValueError class and printing it at the same time. This means the init and str magic methods will be called.", "The value that caused the exception to be raised is set as an attribute called value in the IntFloatValueError class. When the str magic method is called, an error message informing the user that the value passed to the init of CustomIntFloatDict is invalid. The user will now know what they have to do to rectify this error.", "If no exception is raised, i.e. if every val from the zipped object is of type int or float, they will be set in the dictionary using __setitem__(), with the dict parent class method doing the job for us, as can be shown below.", "What happens if the user enters a type which is not list or tuple with the keys and values?", "Again, this example is somewhat contrived, but will showcase how custom exception classes can be used.", "If the user does not specify the keys and values as either a list or tuple, a KeyValueConstructError exception will be raised. The purpose of this exception class is to inform the user that in order to get keys and values into the CustomIntFloatDict object, a list or tuple must be specified to the init constructor in the CustomIntFloatDict class.", "In the example shown, a set has been passed as the second argument to the init constrictor, which causes the custom KeyValueConstructError exception to be raised. Usefully, the error message which is displayed informs the user that the keys and values need to be passed as either a list or tuple.", "When the exception is raised, again, an instance of the KeyValueConstructError is created, with key and value passed as arguments to the KeyValueConstructError constructor. These are set as key and value attributes in the KeyValueConstructError, and used in the __str__ method to produce a useful error message when the object is printed.", "Furthermore, I have even included the datatypes of the objects that have been added to the init constructor to provide enhanced clarity.", "CustomIntFloatDict inherits from dict. This means it will behave exactly like a dictionary except in the places where we choose to selectively modify its behavior.", "__setitem__ is the magic method that is invoked when we set the key and value in a dictionary. In our implementation of setitem, we validate that the value is of type int or float, before it can be set in the dictionary. If it is not, we can make use, once more, of the IntFloatValueError exception class. Here, we can see that when we try to set the string \u2018bad_value\u2019 as a value in the dictionary test_4, an exception is raised.", "The code for this tutorial is shown below in the Github gist and available here.", "Custom exceptions enhance the usability of a class. An exception class should have init and str magic methods which are called automatically during the exception handling process. It is completely up to us what we want our custom error class to do. The methods shown include inspecting an object and printing a useful error message. In both cases, the exception classes make it easier for users of the class to handle errors when they occur!", "Your home for data science. A Medium publication sharing concepts, ideas and codes.", "Articles on Data Science and Programming https://github.com/StephenFordham"], "all_outgoing_urls": [{"url": "https://rsci.app.link/?%24canonical_url=https%3A%2F%2Fmedium.com%2Fp%2Fbfa346629bca&%7Efeature=LoOpenInAppButton&%7Echannel=ShowPostUnderCollection&source=---two_column_layout_nav----------------------------------", "anchor_text": "Open in app"}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign up"}, {"url": "https://medium.com/m/signin?operation=login&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign In"}, {"url": "https://medium.com/?source=---two_column_layout_nav----------------------------------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Fmedium.com%2Fnew-story&source=---two_column_layout_nav-----------------------new_post_sidenav-----------", "anchor_text": "Write"}, {"url": "https://medium.com/search?source=---two_column_layout_nav----------------------------------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign up"}, {"url": "https://medium.com/m/signin?operation=login&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign In"}, {"url": "https://towardsdatascience.com/?source=post_page-----bfa346629bca--------------------------------", "anchor_text": ""}, {"url": "https://towardsdatascience.com/?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Towards Data Science"}, {"url": "https://medium.com/@stephenfordham?source=post_page-----bfa346629bca--------------------------------", "anchor_text": ""}, {"url": "https://medium.com/@stephenfordham?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Stephen Fordham"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F5d3f46276e7e&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&user=Stephen+Fordham&userId=5d3f46276e7e&source=post_page-5d3f46276e7e----bfa346629bca---------------------follow_byline-----------", "anchor_text": "Follow"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=--------------------------bookmark_header-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=--------------------------bookmark_header-----------", "anchor_text": "Save"}, {"url": "https://unsplash.com/@sigmund", "anchor_text": "Sigmund"}, {"url": "https://unsplash.com/photos/By-tZImt0Ms", "anchor_text": "Unsplash"}, {"url": "https://gist.github.com/StephenFordham/8ea287187a0fde02a8ee82d5a1f2039f", "anchor_text": "here"}, {"url": "https://gist.github.com/StephenFordham/549973c9a6099914d2758e3e144e19fa", "anchor_text": "here"}, {"url": "https://medium.com/tag/data-science?source=post_page-----bfa346629bca---------------data_science-----------------", "anchor_text": "Data Science"}, {"url": "https://medium.com/tag/programming?source=post_page-----bfa346629bca---------------programming-----------------", "anchor_text": "Programming"}, {"url": "https://medium.com/tag/towards-data-science?source=post_page-----bfa346629bca---------------towards_data_science-----------------", "anchor_text": "Towards Data Science"}, {"url": "https://medium.com/tag/python?source=post_page-----bfa346629bca---------------python-----------------", "anchor_text": "Python"}, {"url": "https://medium.com/tag/machine-learning?source=post_page-----bfa346629bca---------------machine_learning-----------------", "anchor_text": "Machine Learning"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&user=Stephen+Fordham&userId=5d3f46276e7e&source=-----bfa346629bca---------------------clap_footer-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&user=Stephen+Fordham&userId=5d3f46276e7e&source=-----bfa346629bca---------------------clap_footer-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&source=--------------------------bookmark_footer-----------", "anchor_text": ""}, {"url": "https://towardsdatascience.com/?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "More from Towards Data Science"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fcollection%2Ftowards-data-science%2Fbfa346629bca&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&collection=Towards+Data+Science&collectionId=7f60cf5620c9&source=post_page-----bfa346629bca---------------------follow_footer-----------", "anchor_text": "Follow"}, {"url": "https://towardsdatascience.com/?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Read more from Towards Data Science"}, {"url": "https://medium.com/?source=post_page-----bfa346629bca--------------------------------", "anchor_text": ""}, {"url": "https://medium.com/about?autoplay=1&source=post_page-----bfa346629bca--------------------------------", "anchor_text": "About"}, {"url": "https://help.medium.com/hc/en-us?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Help"}, {"url": "https://policy.medium.com/medium-terms-of-service-9db0094a1e0f?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Terms"}, {"url": "https://policy.medium.com/medium-privacy-policy-f03bf92035c9?source=post_page-----bfa346629bca--------------------------------", "anchor_text": "Privacy"}, {"url": "https://itunes.apple.com/app/medium-everyones-stories/id828256236?pt=698524&mt=8&ct=post_page&source=post_page-----bfa346629bca--------------------------------", "anchor_text": ""}, {"url": "https://play.google.com/store/apps/details?id=com.medium.reader&source=post_page-----bfa346629bca--------------------------------", "anchor_text": ""}, {"url": "https://medium.com/@stephenfordham?source=---two_column_layout_sidebar----------------------------------", "anchor_text": ""}, {"url": "https://medium.com/@stephenfordham?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Stephen Fordham"}, {"url": "https://medium.com/@stephenfordham/followers?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "977 Followers"}, {"url": "https://github.com/StephenFordham", "anchor_text": "https://github.com/StephenFordham"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F5d3f46276e7e&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&user=Stephen+Fordham&userId=5d3f46276e7e&source=post_page-5d3f46276e7e--two_column_layout_sidebar-----------------------follow_profile-----------", "anchor_text": "Follow"}, {"url": "https://medium.com/m/signin?actionUrl=%2F_%2Fapi%2Fsubscriptions%2Fnewsletters%2Fbd4ed43cae00&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fhow-to-define-custom-exception-classes-in-python-bfa346629bca&newsletterV3=5d3f46276e7e&newsletterV3Id=bd4ed43cae00&user=Stephen+Fordham&userId=5d3f46276e7e&source=---two_column_layout_sidebar-----------------------subscribe_user-----------", "anchor_text": ""}, {"url": "https://help.medium.com/hc/en-us?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Help"}, {"url": "https://medium.statuspage.io/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Status"}, {"url": "https://about.medium.com/creators/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Writers"}, {"url": "https://blog.medium.com/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Blog"}, {"url": "https://medium.com/jobs-at-medium/work-at-medium-959d1a85284e?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Careers"}, {"url": "https://policy.medium.com/medium-privacy-policy-f03bf92035c9?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Privacy"}, {"url": "https://policy.medium.com/medium-terms-of-service-9db0094a1e0f?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Terms"}, {"url": "https://medium.com/about?autoplay=1&source=---two_column_layout_sidebar----------------------------------", "anchor_text": "About"}, {"url": "https://speechify.com/medium?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Text to speech"}]}, "scrape_status": {"code": "1"}}